export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const LOGIN_USER_SUCCEED = 'LOGIN_USER_SUCCEED';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const CURRENT_USER_REQUESTED = 'CURRENT_USER_REQUESTED';

export const REGISTER_USER_REQUESTED = 'REGISTER_USER_REQUESTED';
export const REGISTER_USER_SUCCEED = 'REGISTER_USER_SUCCEED';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const LOGOUT_USER_REQUESTED = 'LOGOUT_USER_REQUESTED';
export const LOGOUT_USER_SUCCEED = 'LOGOUT_USER_SUCCEED';
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED';

export const SINGLE_USER_REQUESTED = 'SINGLE_USER_REQUESTED';
export const SINGLE_USER_SUCCEED = 'SINGLE_USER_SUCCEED';
export const SINGLE_USER_FAILED = 'SINGLE_USER_FAILED';

export const UPDATE_USER_REQUESTED = 'UPDATE_USER_REQUESTED';
export const UPDATE_USER_SUCCEED = 'UPDATE_USER_SUCCEED';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const LIST_POST_REQUESTED = 'LIST_POST_REQUESTED';
export const LIST_POST_SUCCEED = 'LIST_POST_SUCCEED';
export const LIST_POST_FAILED = 'LIST_POST_FAILED';

export const LIST_POST_TAG_REQUESTED = 'LIST_POST_TAG_REQUESTED';
export const LIST_POST_TAG_SUCCEED = 'LIST_POST_TAG_SUCCEED';
export const LIST_POST_TAG_FAILED = 'LIST_POST_TAG_FAILED';

export const LIST_POST_CATEGORY_REQUESTED = 'LIST_POST_CATEGORY_REQUESTED';
export const LIST_POST_CATEGORY_SUCCEED = 'LIST_POST_CATEGORY_SUCCEED';
export const LIST_POST_CATEGORY_FAILED = 'LIST_POST_CATEGORY_FAILED';

export const LIST_POST_USER_REQUESTED = 'LIST_POST_USER_REQUESTED';
export const LIST_POST_USER_SUCCEED = 'LIST_POST_USER_SUCCEED';
export const LIST_POST_USER_FAILED = 'LIST_POST_USER_FAILED';

export const LIST_POST_FAVORITED_REQUESTED = 'LIST_POST_FAVORITED_REQUESTED';
export const LIST_POST_FAVORITED_SUCCEED = 'LIST_POST_FAVORITED_SUCCEED';
export const LIST_POST_FAVORITED_FAILED = 'LIST_POST_FAVORITED_FAILED';

export const SINGLE_POST_REQUESTED = 'SINGLE_POST_REQUESTED';
export const SINGLE_POST_SUCCEED = 'SINGLE_POST_SUCCEED';
export const SINGLE_POST_FAILED = 'SINGLE_POST_FAILED';

export const LIST_TAG_REQUESTED = 'LIST_TAG_REQUESTED';
export const LIST_TAG_SUCCEED = 'LIST_TAG_SUCCEED';
export const LIST_TAG_FAILED = 'LIST_TAG_FAILED';

export const SINGLE_TAG_REQUESTED = 'SINGLE_TAG_REQUESTED';
export const SINGLE_TAG_SUCCEED = 'SINGLE_TAG_SUCCEED';
export const SINGLE_TAG_FAILED = 'SINGLE_TAG_FAILED';

export const LIST_CATEGORY_REQUESTED = 'LIST_CATEGORY_REQUESTED';
export const LIST_CATEGORY_SUCCEED = 'LIST_CATEGORY_SUCCEED';
export const LIST_CATEGORY_FAILED = 'LIST_CATEGORY_FAILED';

export const SINGLE_CATEGORY_REQUESTED = 'SINGLE_CATEGORY_REQUESTED';
export const SINGLE_CATEGORY_SUCCEED = 'SINGLE_CATEGORY_SUCCEED';
export const SINGLE_CATEGORY_FAILED = 'SINGLE_CATEGORY_FAILED';

export const LIST_COMMENT_REQUESTED = 'LIST_COMMENT_REQUESTED';
export const LIST_COMMENT_SUCCEED = 'LIST_COMMENT_SUCCEED';
export const LIST_COMMENT_FAILED = 'LIST_COMMENT_FAILED';
